name: PyPI

on:
  release:
    types:
      - created

jobs:
  job:
    name: PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install poetry
      - name: Publish package
        run: |
          poetry config pypi-AgEIcHlwaS5vcmcCJGIxNWE5M2VjLTY5MzgtNDJkYi04ZDNlLTNiMGM5M2Y3ZjlmNAACJXsicGVybWlzc2lvbnMiOiAidXNlciIsICJ2ZXJzaW9uIjogMX0AAAYgXIe1f-9hJBj0aceVv6wALu3Zx6jAYYJ1tCytayuk8wA ${{ secrets.PYPI_TOKEN }}
          poetry publish --build
